import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Header from "@/components/Header";

const inter = Karla({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="px-8">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
